#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "hybrid_darker"
    background = "dark"
    timeoutlen = 200
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = true
    enable_neomake = false
    enable_ale = true

[[custom_plugins]]
  name = "maxaudron/hybrid_darker.vim"
  merged = 0

[[custom_plugins]]
  name = "tpope/vim-fugitive"
  merged = 0

[[custom_plugins]]
  name = "airblade/vim-gitgutter"
  merged = 0

[[custom_plugins]]
  name = "chrisbra/Colorizer"
  merged = 0

[[custom_plugins]]
  name = "xolox/vim-session"
  merged = 0

[[custom_plugins]]
  name = "xolox/vim-misc"
  merged = 0

[[custom_plugins]]
name = "hashivim/vim-terraform"
merged = 0

[[layers]]
name = "ctrlp"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'git'

[[layers]]
name = 'tmux'

[[layers]]
name = 'lang#haskell'
[[layers]]
name = 'lang#dockerfile'
[[layers]]
name = 'lang#c'
[[layers]]
name = 'lang#csharp'
[[layers]]
name = 'lang#html'
[[layers]]
name = 'lang#javascript'
[[layers]]
name = 'lang#latex'
[[layers]]
name = 'lang#markdown'
[[layers]]
name = 'lang#python'
[[layers]]
name = 'lang#sh'
[[layers]]
name = 'lang#typescript'
