# Don't print a new line at the start of the prompt
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
symbol = " \uf101"

[cmd_duration]
min_time = 500
prefix = ""

[directory]
truncation_length = 8
style = "2"
